export const ADD_INGEDIENT = "ADD_INGEDIENT";
export const REMOVE_INGEDIENT = "REMOVE_INGEDIENT";
export const SET_INGREDIENT = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';  

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL';