export const ADD_INGEDIENT = "ADD_INGEDIENT";
export const REMOVE_INGEDIENT = "REMOVE_INGEDIENT";
export const SET_INGREDIENT = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';  
